"""
rebuild-index.py — scan designs/ and effects/ folders and regenerate the
data files that the navigator HTMLs read.

Outputs (overwritten each run):
  designs/designs.json + designs/designs.js   — window.__DESIGNS__
  effects/effects.json + effects/effects.js   — window.__EFFECTS__
  effects/tag-axis.js                         — window.TAG_AXIS + AXIS_ORDER

Reads (must exist):
  tag-axis.json                               — 5-axis spec, source of truth

Each NNN-slug folder needs an index.html to be included; if a meta.json is
present it provides title/description/tags/etc. — otherwise sensible defaults
are derived from the folder name. Folders without index.html are silently
skipped (work-in-progress scrapes won't appear in the gallery).

Run after adding / editing any folder; also invoked by:
  - finalize.py            (full pipeline: rebuild + package + overlay)
  - scrape-url.py          (after each scrape, unless --no-rebuild)

This is a 1:1 Python port of the old rebuild-index.ps1, kept cross-platform
so Linux/macOS contributors aren't blocked by PowerShell.
"""
import sys, io, json, re
from pathlib import Path

if sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf8"):
    try:
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
    except Exception:
        pass

ROOT = Path(__file__).resolve().parent
GEN_HEADER = "// Auto-generated by rebuild-index.py. Do not edit by hand."


def _load_meta(folder: Path) -> dict:
    """Read meta.json if present; return {} otherwise. Bad JSON warns + returns {}."""
    m = folder / "meta.json"
    if not m.exists():
        return {}
    try:
        return json.loads(m.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"  warning: {m} parse error: {e}", file=sys.stderr)
        return {}


def _write_text(path: Path, text: str) -> None:
    """Write UTF-8 without BOM, matching the old PowerShell output bytes."""
    path.write_bytes(text.encode("utf-8"))


def _write_json_and_js(json_path: Path, js_path: Path, var_name: str, data: list) -> None:
    """Emit both `<name>.json` and `<name>.js` (the latter sets window.<var_name>).

    The .js sibling exists so the navigator pages also work under file:// where
    fetch() is blocked by CORS — a <script src=...> tag isn't.
    """
    body = json.dumps(data, ensure_ascii=False, indent=2)
    _write_text(json_path, body + "\n")
    _write_text(js_path, f"{GEN_HEADER}\nwindow.{var_name} = {body};\n")


WACZ_VIEWER_MARKER = "<!-- auto-generated WACZ viewer — rebuild-index.py regenerates this -->"


def _generate_wacz_viewer(folder: Path, wacz_filename: str, title: str, source_url: str) -> None:
    """Emit folder/index.html that mounts <replay-web-page> over the WACZ archive.

    Triggered when a folder contains *.wacz but no hand-written index.html (or one
    that still carries the auto-marker). Regenerating is idempotent — same content
    is written each run so git diffs stay clean.

    Service workers can't register under file://, so the viewer only works when sc2
    is served via a local http.server. The replay-web-page library is self-hosted at
    designs/_replay/ (shared across all wacz designs) — CDN-hosted SW is blocked by
    cross-origin SW registration restrictions.
    """
    safe_title = title.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    safe_src   = source_url.replace('"', "&quot;")
    safe_wacz  = wacz_filename.replace('"', "&quot;")
    html = f"""<!doctype html>
<html lang="en">
<head>
{WACZ_VIEWER_MARKER}
<meta charset="utf-8">
<title>{safe_title} — WACZ replay</title>
<style>
  html, body {{ margin: 0; height: 100%; background: #000; color: #ddd;
                font-family: -apple-system, "Segoe UI", "Microsoft YaHei", sans-serif; }}
  replay-web-page {{ display: block; width: 100%; height: 100vh; }}
  .hint {{ position: fixed; top: 8px; left: 8px; right: 8px; padding: 10px 14px;
           background: rgba(20,22,30,.9); border: 1px solid #2a2d38; border-radius: 8px;
           font-size: 12px; line-height: 1.5; z-index: 1; }}
  .hint code {{ background: #262a36; padding: 1px 6px; border-radius: 4px; font-size: 11.5px; }}
  .hint a {{ color: #7aa2f7; }}
  body.ready .hint {{ display: none; }}
</style>
</head>
<body>
<div class="hint">
  WACZ replay 需要本地 HTTP 服务（不能 file://）。
  在 sc2 根目录跑 <code>python -m http.server</code>，
  然后通过 <code>http://localhost:8000/designs/{folder.name}/index.html</code> 打开。
</div>
<replay-web-page
  source="{safe_wacz}"
  url="{safe_src}"
  embed="replayonly"
  replayBase="../_replay/replay/"
></replay-web-page>
<script src="../_replay/ui.js"></script>
<script>
  // hide the hint once replay-web-page successfully mounts
  customElements.whenDefined && customElements.whenDefined('replay-web-page')
    .then(() => document.body.classList.add('ready'));
</script>
</body>
</html>
"""
    (folder / "index.html").write_text(html, encoding="utf-8")


def _maybe_generate_wacz_viewer(folder: Path, meta: dict) -> bool:
    """If folder has a .wacz and the index.html is either missing or auto-generated,
    (re)write the viewer. Returns True if a viewer was emitted (so the caller knows
    an index.html now exists)."""
    wacz_files = sorted(folder.glob("*.wacz"))
    if not wacz_files:
        return False
    index = folder / "index.html"
    can_overwrite = (not index.exists()) or (WACZ_VIEWER_MARKER in
                                              index.read_text(encoding="utf-8", errors="ignore"))
    if not can_overwrite:
        # user hand-wrote an index.html — respect it
        return False
    title = meta.get("title") or folder.name
    source_url = meta.get("sourceUrl") or ""
    _generate_wacz_viewer(folder, wacz_files[0].name, title, source_url)
    return True


def rebuild_designs(root: Path) -> int:
    """Index designs/ — return the count of mirrors written."""
    designs_dir = root / "designs"
    designs_dir.mkdir(exist_ok=True)
    designs = []
    for d in sorted(p for p in designs_dir.iterdir() if p.is_dir()):
        meta = _load_meta(d)
        # WACZ folders: auto-generate the viewer index.html before the existence
        # check below. This is what lets `.wacz`-only folders show up in the
        # navigator without any per-folder hand-writing.
        _maybe_generate_wacz_viewer(d, meta)
        if not (d / "index.html").exists():
            continue
        # `.skip-index` opts a local-only mirror out of the gallery — used
        # when a remote teammate already published a better mirror of the
        # same site and we want to keep the local capture as a personal
        # archive without polluting the shared index.
        if (d / ".skip-index").exists():
            continue
        # href + preview are relative to designs/ (where the .json/.js live),
        # so designs/index.html can <iframe> them without a designs/ prefix.
        preview = f"{d.name}/preview.png" if (d / "preview.png").exists() else ""
        designs.append({
            "folder":      d.name,
            "title":       meta.get("title")       or d.name,
            "description": meta.get("description") or "",
            "sourceUrl":   meta.get("sourceUrl")   or "",
            "savedAt":     meta.get("savedAt")     or "",
            "tags":        list(meta.get("tags") or []),
            "href":        f"{d.name}/index.html",
            "preview":     preview,
        })
    _write_json_and_js(
        designs_dir / "designs.json",
        designs_dir / "designs.js",
        "__DESIGNS__",
        designs,
    )
    print(f"Indexed {len(designs)} design(s). Output: "
          f"{designs_dir / 'designs.json'} + {designs_dir / 'designs.js'}")
    return len(designs)


def rebuild_effects(root: Path) -> int:
    """Index effects/ — return the count of effects written."""
    effects_dir = root / "effects"
    if not effects_dir.exists():
        return 0
    effects = []
    for d in sorted(p for p in effects_dir.iterdir() if p.is_dir()):
        if not (d / "index.html").exists():
            continue
        if (d / ".skip-index").exists():
            continue
        meta = _load_meta(d)
        m = re.match(r"^(\d+)-", d.name)
        num = m.group(1) if m else ""
        # `order` defaults to int(num); meta.order overrides if present + valid.
        default_order = int(num) if num else 9999
        try:
            order = int(meta.get("order", default_order))
        except (TypeError, ValueError):
            order = default_order
        effects.append({
            "num":         num,
            "folder":      d.name,
            "title":       meta.get("title")       or d.name,
            "subtitle":    meta.get("subtitle")    or "",
            "description": meta.get("description") or "",
            "tech":        meta.get("tech")        or "",
            "tags":        list(meta.get("tags") or []),
            "previewHref": meta.get("previewHref") or "",
            "sourceUrl":   meta.get("sourceUrl")   or "",
            "localMirror": meta.get("localMirror") or "",
            "order":       order,
        })
    _write_json_and_js(
        effects_dir / "effects.json",
        effects_dir / "effects.js",
        "__EFFECTS__",
        effects,
    )
    print(f"Indexed {len(effects)} effect(s). Output: "
          f"{effects_dir / 'effects.json'} + {effects_dir / 'effects.js'}")
    return len(effects)


def emit_tag_axis_js(root: Path) -> None:
    """Read tag-axis.json + emit effects/tag-axis.js for the gallery + viewer."""
    spec_path = root / "tag-axis.json"
    if not spec_path.exists():
        print(f"warning: {spec_path} missing — gallery TAG_AXIS will be stale",
              file=sys.stderr)
        return
    try:
        spec = json.loads(spec_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"warning: tag-axis.json malformed ({e})", file=sys.stderr)
        return
    tag_axis = {}
    axis_order = {}
    for axis in spec["axes"]:
        axis_order[axis["name"]] = int(axis["displayOrder"])
        for t in axis["tags"]:
            tag_axis[t] = axis["name"]
    axis_order["_other"] = 9
    out = root / "effects" / "tag-axis.js"
    out.parent.mkdir(exist_ok=True)
    body = (
        f"// Auto-generated by rebuild-index.py from tag-axis.json. Do not edit by hand.\n"
        f"window.TAG_AXIS = {json.dumps(tag_axis, ensure_ascii=False, separators=(',', ':'))};\n"
        f"window.AXIS_ORDER = {json.dumps(axis_order, ensure_ascii=False, separators=(',', ':'))};\n"
    )
    _write_text(out, body)
    print(f"Emitted tag axis map: {out}")


def main() -> int:
    rebuild_designs(ROOT)
    rebuild_effects(ROOT)
    emit_tag_axis_js(ROOT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
