"""
rebuild-index.py — scan designs/ and effects/ folders and regenerate the
data files that the navigator HTMLs read.

Outputs (overwritten each run):
  designs/designs.json + designs/designs.js   — window.__DESIGNS__
  effects/effects.json + effects/effects.js   — window.__EFFECTS__
  effects/tag-axis.js                         — window.TAG_AXIS + AXIS_ORDER

Reads (must exist):
  tag-axis.json                               — 5-axis spec, source of truth

Each NNN-slug folder needs an index.html to be included; if a meta.json is
present it provides title/description/tags/etc. — otherwise sensible defaults
are derived from the folder name. Folders without index.html are silently
skipped (work-in-progress scrapes won't appear in the gallery).

Run after adding / editing any folder; also invoked by:
  - finalize.py            (full pipeline: rebuild + package + overlay)
  - scrape-url.py          (after each scrape, unless --no-rebuild)

This is a 1:1 Python port of the old rebuild-index.ps1, kept cross-platform
so Linux/macOS contributors aren't blocked by PowerShell.
"""
import sys, io, json, re
from pathlib import Path

if sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf8"):
    try:
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
    except Exception:
        pass

ROOT = Path(__file__).resolve().parent
GEN_HEADER = "// Auto-generated by rebuild-index.py. Do not edit by hand."


def _load_meta(folder: Path) -> dict:
    """Read meta.json if present; return {} otherwise. Bad JSON warns + returns {}."""
    m = folder / "meta.json"
    if not m.exists():
        return {}
    try:
        return json.loads(m.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"  warning: {m} parse error: {e}", file=sys.stderr)
        return {}


def _write_text(path: Path, text: str) -> None:
    """Write UTF-8 without BOM, matching the old PowerShell output bytes."""
    path.write_bytes(text.encode("utf-8"))


def _write_json_and_js(json_path: Path, js_path: Path, var_name: str, data: list) -> None:
    """Emit both `<name>.json` and `<name>.js` (the latter sets window.<var_name>).

    The .js sibling exists so the navigator pages also work under file:// where
    fetch() is blocked by CORS — a <script src=...> tag isn't.
    """
    body = json.dumps(data, ensure_ascii=False, indent=2)
    _write_text(json_path, body + "\n")
    _write_text(js_path, f"{GEN_HEADER}\nwindow.{var_name} = {body};\n")


def rebuild_designs(root: Path) -> int:
    """Index designs/ — return the count of mirrors written."""
    designs_dir = root / "designs"
    designs_dir.mkdir(exist_ok=True)
    designs = []
    for d in sorted(p for p in designs_dir.iterdir() if p.is_dir()):
        if not (d / "index.html").exists():
            continue
        # `.skip-index` opts a local-only mirror out of the gallery — used
        # when a remote teammate already published a better mirror of the
        # same site and we want to keep the local capture as a personal
        # archive without polluting the shared index.
        if (d / ".skip-index").exists():
            continue
        meta = _load_meta(d)
        # href + preview are relative to designs/ (where the .json/.js live),
        # so designs/index.html can <iframe> them without a designs/ prefix.
        preview = f"{d.name}/preview.png" if (d / "preview.png").exists() else ""
        designs.append({
            "folder":      d.name,
            "title":       meta.get("title")       or d.name,
            "description": meta.get("description") or "",
            "sourceUrl":   meta.get("sourceUrl")   or "",
            "savedAt":     meta.get("savedAt")     or "",
            "tags":        list(meta.get("tags") or []),
            "href":        f"{d.name}/index.html",
            "preview":     preview,
        })
    _write_json_and_js(
        designs_dir / "designs.json",
        designs_dir / "designs.js",
        "__DESIGNS__",
        designs,
    )
    print(f"Indexed {len(designs)} design(s). Output: "
          f"{designs_dir / 'designs.json'} + {designs_dir / 'designs.js'}")
    return len(designs)


def rebuild_effects(root: Path) -> int:
    """Index effects/ — return the count of effects written."""
    effects_dir = root / "effects"
    if not effects_dir.exists():
        return 0
    effects = []
    for d in sorted(p for p in effects_dir.iterdir() if p.is_dir()):
        if not (d / "index.html").exists():
            continue
        if (d / ".skip-index").exists():
            continue
        meta = _load_meta(d)
        m = re.match(r"^(\d+)-", d.name)
        num = m.group(1) if m else ""
        # `order` defaults to int(num); meta.order overrides if present + valid.
        default_order = int(num) if num else 9999
        try:
            order = int(meta.get("order", default_order))
        except (TypeError, ValueError):
            order = default_order
        effects.append({
            "num":         num,
            "folder":      d.name,
            "title":       meta.get("title")       or d.name,
            "subtitle":    meta.get("subtitle")    or "",
            "description": meta.get("description") or "",
            "tech":        meta.get("tech")        or "",
            "tags":        list(meta.get("tags") or []),
            "previewHref": meta.get("previewHref") or "",
            "sourceUrl":   meta.get("sourceUrl")   or "",
            "localMirror": meta.get("localMirror") or "",
            "order":       order,
        })
    _write_json_and_js(
        effects_dir / "effects.json",
        effects_dir / "effects.js",
        "__EFFECTS__",
        effects,
    )
    print(f"Indexed {len(effects)} effect(s). Output: "
          f"{effects_dir / 'effects.json'} + {effects_dir / 'effects.js'}")
    return len(effects)


def emit_tag_axis_js(root: Path) -> None:
    """Read tag-axis.json + emit effects/tag-axis.js for the gallery + viewer."""
    spec_path = root / "tag-axis.json"
    if not spec_path.exists():
        print(f"warning: {spec_path} missing — gallery TAG_AXIS will be stale",
              file=sys.stderr)
        return
    try:
        spec = json.loads(spec_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"warning: tag-axis.json malformed ({e})", file=sys.stderr)
        return
    tag_axis = {}
    axis_order = {}
    for axis in spec["axes"]:
        axis_order[axis["name"]] = int(axis["displayOrder"])
        for t in axis["tags"]:
            tag_axis[t] = axis["name"]
    axis_order["_other"] = 9
    out = root / "effects" / "tag-axis.js"
    out.parent.mkdir(exist_ok=True)
    body = (
        f"// Auto-generated by rebuild-index.py from tag-axis.json. Do not edit by hand.\n"
        f"window.TAG_AXIS = {json.dumps(tag_axis, ensure_ascii=False, separators=(',', ':'))};\n"
        f"window.AXIS_ORDER = {json.dumps(axis_order, ensure_ascii=False, separators=(',', ':'))};\n"
    )
    _write_text(out, body)
    print(f"Emitted tag axis map: {out}")


def main() -> int:
    rebuild_designs(ROOT)
    rebuild_effects(ROOT)
    emit_tag_axis_js(ROOT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
