$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $MyInvocation.MyCommand.Path

# === designs/ → designs.json (root) ===
$designsDir = Join-Path $root "designs"
if (-not (Test-Path $designsDir)) {
    New-Item -ItemType Directory -Path $designsDir | Out-Null
}

$designs = @()
Get-ChildItem -Path $designsDir -Directory | Sort-Object Name | ForEach-Object {
    $folder = $_.Name
    $folderPath = $_.FullName

    $indexPath = Join-Path $folderPath "index.html"
    if (-not (Test-Path $indexPath)) { return }

    $metaPath = Join-Path $folderPath "meta.json"
    $title = $folder
    $description = ""
    $sourceUrl = ""
    $savedAt = ""
    $tags = @()

    if (Test-Path $metaPath) {
        try {
            $meta = Get-Content $metaPath -Raw -Encoding UTF8 | ConvertFrom-Json
            if ($meta.title)       { $title = $meta.title }
            if ($meta.description) { $description = $meta.description }
            if ($meta.sourceUrl)   { $sourceUrl = $meta.sourceUrl }
            if ($meta.savedAt)     { $savedAt = $meta.savedAt }
            if ($meta.tags)        { $tags = @($meta.tags) }
        } catch {
            Write-Warning "Failed to parse $metaPath : $_"
        }
    }

    $previewPath = Join-Path $folderPath "preview.png"
    $preview = if (Test-Path $previewPath) { "designs/$folder/preview.png" } else { "" }

    $designs += [PSCustomObject]@{
        folder      = $folder
        title       = $title
        description = $description
        sourceUrl   = $sourceUrl
        savedAt     = $savedAt
        tags        = $tags
        href        = "designs/$folder/index.html"
        preview     = $preview
    }
}

$designsJson = $designs | ConvertTo-Json -Depth 5
if ($designs.Count -eq 0) { $designsJson = "[]" }
elseif ($designs.Count -eq 1) { $designsJson = "[$designsJson]" }

$designsOut = Join-Path $root "designs.json"
[System.IO.File]::WriteAllText($designsOut, $designsJson, [System.Text.UTF8Encoding]::new($false))

Write-Host ("Indexed {0} design(s). Output: {1}" -f $designs.Count, $designsOut) -ForegroundColor Green

# === effects/ → effects/effects.json ===
$effectsDir = Join-Path $root "effects"
if (Test-Path $effectsDir) {
    $effects = @()
    Get-ChildItem -Path $effectsDir -Directory | Sort-Object Name | ForEach-Object {
        $folder = $_.Name
        $folderPath = $_.FullName

        $indexPath = Join-Path $folderPath "index.html"
        if (-not (Test-Path $indexPath)) { return }

        $num = ""
        if ($folder -match '^(\d+)-') { $num = $matches[1] }

        $title       = $folder
        $subtitle    = ""
        $description = ""
        $tech        = ""
        $tags        = @()
        $previewHref = ""
        $sourceUrl   = ""
        $localMirror = ""
        $order       = if ($num -match '^\d+$') { [int]$num } else { 9999 }

        $metaPath = Join-Path $folderPath "meta.json"
        if (Test-Path $metaPath) {
            try {
                $meta = Get-Content $metaPath -Raw -Encoding UTF8 | ConvertFrom-Json
                if ($meta.title)        { $title = $meta.title }
                if ($meta.subtitle)     { $subtitle = $meta.subtitle }
                if ($meta.description)  { $description = $meta.description }
                if ($meta.tech)         { $tech = $meta.tech }
                if ($meta.tags)         { $tags = @($meta.tags) }
                if ($meta.previewHref)  { $previewHref = $meta.previewHref }
                if ($meta.sourceUrl)    { $sourceUrl = $meta.sourceUrl }
                if ($meta.localMirror)  { $localMirror = $meta.localMirror }
                if ($null -ne $meta.order) {
                    try { $order = [int]$meta.order } catch {}
                }
            } catch {
                Write-Warning "Failed to parse $metaPath : $_"
            }
        }

        $effects += [PSCustomObject]@{
            num         = $num
            folder      = $folder
            title       = $title
            subtitle    = $subtitle
            description = $description
            tech        = $tech
            tags        = $tags
            previewHref = $previewHref
            sourceUrl   = $sourceUrl
            localMirror = $localMirror
            order       = $order
        }
    }

    $effectsJson = $effects | ConvertTo-Json -Depth 5
    if ($effects.Count -eq 0) { $effectsJson = "[]" }
    elseif ($effects.Count -eq 1) { $effectsJson = "[$effectsJson]" }

    $effectsJsonOut = Join-Path $effectsDir "effects.json"
    [System.IO.File]::WriteAllText($effectsJsonOut, $effectsJson, [System.Text.UTF8Encoding]::new($false))

    # Also emit effects.js so index.html works under file:// (script tags don't need a server)
    $effectsJsBody = "// Auto-generated by rebuild-index.ps1. Do not edit by hand.`r`nwindow.__EFFECTS__ = $effectsJson;`r`n"
    $effectsJsOut = Join-Path $effectsDir "effects.js"
    [System.IO.File]::WriteAllText($effectsJsOut, $effectsJsBody, [System.Text.UTF8Encoding]::new($false))

    Write-Host ("Indexed {0} effect(s). Output: {1} + {2}" -f $effects.Count, $effectsJsonOut, $effectsJsOut) -ForegroundColor Green
}
