// Auto-generated by rebuild-index.py. Do not edit by hand.
window.__DESIGNS__ = [
  {
    "folder": "001-talamus",
    "title": "Talamus",
    "description": "",
    "sourceUrl": "https://talamus.pro/",
    "savedAt": "2026-05-06",
    "tags": [],
    "href": "001-talamus/index.html",
    "preview": ""
  },
  {
    "folder": "002-shift5",
    "title": "Shift5",
    "description": "",
    "sourceUrl": "https://shift5.io/",
    "savedAt": "2026-05-06",
    "tags": [],
    "href": "002-shift5/index.html",
    "preview": ""
  },
  {
    "folder": "003-armateursdefrance",
    "title": "Armateurs de France",
    "description": "",
    "sourceUrl": "https://www.armateursdefrance.org/",
    "savedAt": "2026-05-06",
    "tags": [],
    "href": "003-armateursdefrance/index.html",
    "preview": ""
  },
  {
    "folder": "004-omrbeauty",
    "title": "OMR Beauty",
    "description": "",
    "sourceUrl": "https://omrbeauty.com/",
    "savedAt": "2026-05-07",
    "tags": [],
    "href": "004-omrbeauty/index.html",
    "preview": ""
  },
  {
    "folder": "005-goodlifemeds",
    "title": "Good Life Meds",
    "description": "",
    "sourceUrl": "https://www.goodlifemeds.com/",
    "savedAt": "2026-05-07",
    "tags": [],
    "href": "005-goodlifemeds/index.html",
    "preview": ""
  },
  {
    "folder": "006-flowerknows",
    "title": "Flower Knows",
    "description": "",
    "sourceUrl": "https://flowerknows.co/",
    "savedAt": "2026-05-09",
    "tags": [],
    "href": "006-flowerknows/index.html",
    "preview": ""
  },
  {
    "folder": "007-fluidglass",
    "title": "Fluid Glass",
    "description": "",
    "sourceUrl": "https://fluid.glass/",
    "savedAt": "2026-05-09",
    "tags": [],
    "href": "007-fluidglass/index.html",
    "preview": ""
  },
  {
    "folder": "008-donmolinico",
    "title": "Don Molinico",
    "description": "Nuxt 2 客户端路由 SPA。镜像只能用来取源/抽块——预览界面会显示 PAGE NOT FOUND，因为 Vue Router 按 location.pathname 配路由，本地 URL 对不上 /products。HTML 骨架 + 65 个 JS chunk + 字体都在本地。",
    "sourceUrl": "https://www.donmolinico.es/products/",
    "savedAt": "2026-05-14",
    "tags": [
      "spa",
      "nuxt",
      "reference-only"
    ],
    "href": "008-donmolinico/index.html",
    "preview": "008-donmolinico/preview.png"
  },
  {
    "folder": "009-obsidianassembly",
    "title": "Obsidian Assembly",
    "description": "Nuxt 3 SPA。镜像本身可以正常渲染（含 hero blur 字 + nav + 多个 placeholder section），用了 5 步手工补救：补抓 7 个 CSS chunk、复制 images/fonts 目录到镜像根、JS/CSS 里 /images/ → ./images/ 路径改写、注入 <base href=/designs/009.../> 锁定 Nuxt history.replaceState 后的相对路径基准、补抓 35 张 lazy 图。",
    "sourceUrl": "https://obsidianassembly.com/",
    "savedAt": "2026-05-14",
    "tags": [
      "spa",
      "nuxt",
      "experimental-effects"
    ],
    "href": "009-obsidianassembly/index.html",
    "preview": "009-obsidianassembly/preview.png"
  },
  {
    "folder": "010-fluid-folding-door",
    "title": "Fluid Glass - Fluid Folding Door",
    "description": "fluid.glass /collection/fluid-folding-door 产品详情页：左侧大幅产品图 + 右侧粘性 sidebar（产品标签 / 标题 / 介绍 / GET A QUOTE CTA）。开屏 splash 动画淡出后呈现 hero；下方依次为 BENEFITS / INFORMATION / CONFIGURATIONS 三段 anchor 切换的产品信息。配色：奶白底 #f1ede6 + 深灰文字，serif + sans 混排，整体克制、画廊感强",
    "sourceUrl": "https://fluid.glass/collection/fluid-folding-door",
    "savedAt": "2026-05-14",
    "tags": [
      "product-detail",
      "luxury",
      "sticky-sidebar",
      "splash-intro",
      "nuxt3"
    ],
    "href": "010-fluid-folding-door/index.html",
    "preview": "010-fluid-folding-door/preview.png"
  },
  {
    "folder": "011-donmolinico-home",
    "title": "Don Molinico — homepage",
    "description": "Nuxt 2 客户端路由 SPA 主页镜像。按 nuxt-spa-mirror recipe 修活：injected <base href>、改 webpack publicPath f.p / __NUXT__.basePath / assetsPath、补 10 个 lazy chunk、改 url(/fonts/...) → url(./fonts/...)。本地 server 渲染与原站一致。",
    "sourceUrl": "https://www.donmolinico.es/",
    "savedAt": "2026-05-15",
    "tags": [
      "spa",
      "nuxt"
    ],
    "href": "011-donmolinico-home/index.html",
    "preview": "011-donmolinico-home/preview.png"
  },
  {
    "folder": "012-minamassoud",
    "title": "Mina Massoud",
    "description": "",
    "sourceUrl": "https://mina-massoud.com/",
    "savedAt": "2026-05-15",
    "tags": [],
    "href": "012-minamassoud/index.html",
    "preview": "012-minamassoud/preview.png"
  },
  {
    "folder": "013-more-nutrition",
    "title": "More Nutrition",
    "description": "",
    "sourceUrl": "https://more-nutrition.webflow.io/",
    "savedAt": "2026-05-15",
    "tags": [],
    "href": "013-more-nutrition/index.html",
    "preview": "013-more-nutrition/preview.png"
  },
  {
    "folder": "015-lab46",
    "title": "LAB46: Intimate Science",
    "description": "",
    "sourceUrl": "https://lab46.de/en",
    "savedAt": "2026-05-18",
    "tags": [],
    "href": "015-lab46/index.html",
    "preview": "015-lab46/preview.png"
  },
  {
    "folder": "016-theunknown",
    "title": "THE UN KNOWN · Creative Agency Montreal",
    "description": "",
    "sourceUrl": "https://theunknown.tv/en",
    "savedAt": "2026-05-18",
    "tags": [],
    "href": "016-theunknown/index.html",
    "preview": "016-theunknown/preview.png"
  },
  {
    "folder": "017-innoceanberlin",
    "title": "017-innoceanberlin",
    "description": "",
    "sourceUrl": "https://innoceanberlin.com/?ref=siteinspire",
    "savedAt": "2026-05-20",
    "tags": [],
    "href": "017-innoceanberlin/index.html",
    "preview": "017-innoceanberlin/preview.png"
  },
  {
    "folder": "018-viture-beast",
    "title": "018-viture-beast",
    "description": "",
    "sourceUrl": "https://www.viture.jp/beast",
    "savedAt": "2026-05-20",
    "tags": [],
    "href": "018-viture-beast/index.html",
    "preview": "018-viture-beast/preview.png"
  },
  {
    "folder": "019-sunmetalon",
    "title": "Sun Metalon",
    "description": "",
    "sourceUrl": "https://sunmetalon.com/",
    "savedAt": "2026-05-20",
    "tags": [],
    "href": "019-sunmetalon/index.html",
    "preview": "019-sunmetalon/preview.png"
  },
  {
    "folder": "020-fromanother",
    "title": "From Another",
    "description": "",
    "sourceUrl": "https://www.fromanother.love/",
    "savedAt": "2026-05-21",
    "tags": [],
    "href": "020-fromanother/index.html",
    "preview": "020-fromanother/preview.png"
  },
  {
    "folder": "Floema",
    "title": "Floema — Spaces for people, made for life",
    "description": "Sustainable signage & equipment brand. Pixi.js scattered-objects hero, scroll-driven photo collages, audio-driven micro-interactions. Homepage captured as full-page PNG (homepage-full.png) because the live site is a Nuxt SPA with Sanity-CMS images served via /_ipx/ proxy — interactive mirror keeps hero + nav but sub-page CSS chunks are absent.",
    "sourceUrl": "https://www.floema.com/en",
    "savedAt": "2026-05-16",
    "tags": [
      "pixi",
      "nuxt",
      "sanity",
      "scroll-animation",
      "minimal",
      "editorial",
      "brand"
    ],
    "href": "Floema/index.html",
    "preview": ""
  }
];
